version: '3.8'

services:
  mongo:
    container_name: messages-hive
    build:
      context: ./mongodb_replica
      args:
        MONGO_VERSION: latest
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27018
      MONGO_COMMAND: 'mongosh'
    ports:
      - '27018:27018'
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
